/**
 * Word's automatic heading numbering ("Chapter 1", "Chapter 2"… generated by a
 * multilevel list attached to Heading 1, as in Word's "Chapter 1 Heading 1"
 * gallery preset). The number is not text in the document, so mammoth drops
 * it; this computes the labels Word shows so they can be written into the
 * headings. Only numbering definitions and styles are read (numbering.xml,
 * styles.xml); the counters run over the heading paragraphs in document order.
 */

const W_NS = [
  'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  // Strict Open XML.
  'http://purl.oclc.org/ooxml/wordprocessingml/main',
]

export interface NumberingLevel {
  numFmt: string
  lvlText: string
  start: number
  /** Paragraph style this level is attached to (w:pStyle), e.g. "Heading1". */
  pStyle?: string
  /** What follows the number: "tab" (Word's default), "space" or "nothing". */
  suff: string
}

export interface NumberingDefs {
  /** abstractNumId → level index → level. */
  abstract: Map<string, Map<number, NumberingLevel>>
  /** numId → abstractNumId. */
  nums: Map<string, string>
  /** Style numbering: styleId → numId (following w:basedOn). */
  styleNum: Map<string, string>
}

function children(el: Element | Document, local: string): Element[] {
  const out: Element[] = []
  for (const ns of W_NS) out.push(...Array.from(el.getElementsByTagNameNS(ns, local)))
  return out
}

function directChild(el: Element, local: string): Element | undefined {
  return Array.from(el.children).find((c) => c.localName === local && W_NS.includes(c.namespaceURI ?? ''))
}

function wAttr(el: Element | undefined, name: string): string | undefined {
  if (!el) return undefined
  for (const ns of W_NS) {
    const v = el.getAttributeNS(ns, name)
    if (v !== null && v !== '') return v
  }
  return el.getAttribute(`w:${name}`) ?? undefined
}

function parseXml(xml: string | null): Document | null {
  if (!xml || typeof DOMParser === 'undefined') return null
  const doc = new DOMParser().parseFromString(xml, 'application/xml')
  return doc.getElementsByTagName('parsererror').length ? null : doc
}

export function readNumberingDefs(numberingXml: string | null, stylesXml: string | null): NumberingDefs | null {
  const numbering = parseXml(numberingXml)
  if (!numbering) return null
  const abstract = new Map<string, Map<number, NumberingLevel>>()
  for (const a of children(numbering, 'abstractNum')) {
    const id = wAttr(a, 'abstractNumId')
    if (id === undefined) continue
    const levels = new Map<number, NumberingLevel>()
    for (const lvl of children(a, 'lvl')) {
      const ilvl = Number(wAttr(lvl, 'ilvl') ?? '0')
      levels.set(ilvl, {
        numFmt: wAttr(directChild(lvl, 'numFmt'), 'val') ?? 'decimal',
        lvlText: wAttr(directChild(lvl, 'lvlText'), 'val') ?? '',
        start: Number(wAttr(directChild(lvl, 'start'), 'val') ?? '1') || 0,
        pStyle: wAttr(directChild(lvl, 'pStyle'), 'val'),
        suff: wAttr(directChild(lvl, 'suff'), 'val') ?? 'tab',
      })
    }
    abstract.set(id, levels)
  }
  const nums = new Map<string, string>()
  for (const n of children(numbering, 'num')) {
    const id = wAttr(n, 'numId')
    const abs = wAttr(directChild(n, 'abstractNumId'), 'val')
    if (id !== undefined && abs !== undefined) nums.set(id, abs)
  }

  const styleNum = new Map<string, string>()
  const styles = parseXml(stylesXml)
  if (styles) {
    const direct = new Map<string, { numId?: string; basedOn?: string }>()
    for (const st of children(styles, 'style')) {
      const id = wAttr(st, 'styleId')
      if (!id) continue
      const pPr = directChild(st, 'pPr')
      const numPr = pPr ? directChild(pPr, 'numPr') : undefined
      direct.set(id, { numId: wAttr(numPr ? directChild(numPr, 'numId') : undefined, 'val'), basedOn: wAttr(directChild(st, 'basedOn'), 'val') })
    }
    for (const id of direct.keys()) {
      let cur: string | undefined = id
      for (let depth = 0; cur && depth < 10; depth++) {
        const d = direct.get(cur)
        if (d?.numId) {
          styleNum.set(id, d.numId)
          break
        }
        cur = d?.basedOn
      }
    }
  }
  return { abstract, nums, styleNum }
}

const ONES = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']
const TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']
const ORDINAL_WORDS: Record<string, string> = { one: 'first', two: 'second', three: 'third', five: 'fifth', eight: 'eighth', nine: 'ninth', twelve: 'twelfth' }

function cardinal(n: number): string {
  if (n <= 0 || n >= 1000) return String(n)
  if (n >= 100) return `${ONES[Math.floor(n / 100)]} hundred${n % 100 ? ` ${cardinal(n % 100)}` : ''}`
  if (n < 20) return ONES[n]
  return `${TENS[Math.floor(n / 10)]}${n % 10 ? `-${ONES[n % 10]}` : ''}`
}

function ordinalWord(n: number): string {
  const words = cardinal(n)
  return words.replace(/([a-z]+)$/, (last) => ORDINAL_WORDS[last] ?? (last.endsWith('y') ? `${last.slice(0, -1)}ieth` : `${last}th`))
}

function roman(n: number): string {
  if (n <= 0 || n >= 4000) return String(n)
  const table: Array<[number, string]> = [
    [1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'],
    [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I'],
  ]
  let out = ''
  for (const [v, s] of table) while (n >= v) {
    out += s
    n -= v
  }
  return out
}

function letters(n: number): string {
  if (n <= 0) return String(n)
  // Word repeats the letter: A…Z, AA…ZZ, AAA…
  const ch = String.fromCharCode(65 + ((n - 1) % 26))
  return ch.repeat(Math.floor((n - 1) / 26) + 1)
}

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

/** A counter in a w:numFmt ("decimal", "upperRoman", "cardinalText"…). Unknown formats fall back to digits. */
export function formatNumber(n: number, fmt: string): string {
  switch (fmt) {
    case 'upperRoman':
      return roman(n)
    case 'lowerRoman':
      return roman(n).toLowerCase()
    case 'upperLetter':
      return letters(n)
    case 'lowerLetter':
      return letters(n).toLowerCase()
    case 'cardinalText':
      return cap(cardinal(n))
    case 'ordinalText':
      return cap(ordinalWord(n))
    case 'ordinal':
      return `${n}${n % 100 >= 11 && n % 100 <= 13 ? 'th' : ['th', 'st', 'nd', 'rd'][n % 10] ?? 'th'}`
    case 'decimalZero':
      return n < 10 ? `0${n}` : String(n)
    case 'none':
      return ''
    default:
      return String(n)
  }
}

/**
 * Hands out the label for each numbered heading paragraph, in document order,
 * keeping Word's counters (a level restarts when a higher level advances).
 */
export class HeadingNumberer {
  private counters = new Map<string, number[]>()

  constructor(private readonly defs: NumberingDefs | null) {}

  /**
   * The list a heading's numbering belongs to: its style's own numbering, else
   * the level linked to its style (the last one, as mammoth picks it).
   */
  private resolve(styleId: string | null, level: number): { absId: string; levels: Map<number, NumberingLevel> } | null {
    const defs = this.defs
    if (!defs) return null
    if (styleId) {
      const numId = defs.styleNum.get(styleId)
      const absId = numId !== undefined ? defs.nums.get(numId) : undefined
      const levels = absId !== undefined ? defs.abstract.get(absId) : undefined
      if (absId !== undefined && levels) return { absId, levels }
      let linked: { absId: string; levels: Map<number, NumberingLevel> } | null = null
      for (const [id, lv] of defs.abstract) {
        for (const l of lv.values()) if (l.pStyle === styleId) linked = { absId: id, levels: lv }
      }
      if (linked) return linked
    }
    // Numbering set on the paragraph itself (mammoth doesn't say which list): the only list,
    // or else the one list that numbers this level with words around the number ("Chapter %1").
    const all = [...defs.abstract]
    if (all.length === 1) return { absId: all[0][0], levels: all[0][1] }
    const worded = all.filter(([, levels]) => /\p{L}/u.test(levels.get(level)?.lvlText.replace(/%\d/g, '') ?? ''))
    if (worded.length === 1) return { absId: worded[0][0], levels: worded[0][1] }
    return null
  }

  /** The label ("Chapter 3", "IV.", "2.1") and what separates it from the heading text, or null. */
  next(styleId: string | null, level: number): { label: string; separator: string } | null {
    const found = this.resolve(styleId, level)
    const lvl = found?.levels.get(level)
    if (!found || !lvl) return null
    const counts = this.counters.get(found.absId) ?? []
    for (let i = 0; i < level; i++) if (counts[i] === undefined) counts[i] = found.levels.get(i)?.start ?? 1
    counts[level] = counts[level] === undefined ? lvl.start : counts[level] + 1
    counts.length = level + 1
    this.counters.set(found.absId, counts)
    const label = lvl.lvlText
      .replace(/%([1-9])/g, (_, d: string) => {
        const k = Number(d) - 1
        const value = counts[k] ?? found.levels.get(k)?.start ?? 1
        // Word shows an upper level in its own format, except in "legal" style lists (not handled).
        return formatNumber(value, k === level ? lvl.numFmt : found.levels.get(k)?.numFmt ?? 'decimal')
      })
      .trim()
    if (!label) return null
    return { label, separator: lvl.suff === 'nothing' ? '' : ' ' }
  }
}
